### PR TITLE
Jeffery Lockett Training GitHub Branch 

### PR DESCRIPTION
**Pull request by jefferylockett**
Jeff Lockett Branch

### CODE REVIEW

**Comment by danaburt** [comment]
looks good

**Comment by marisaherbert** [comment]
Looks good

**Review by danaburt — COMMENTED** [review]
store id conflict

**Review by marisaherbert — APPROVED** [review]

**Review by LawsonAE — APPROVED** [review]

**Comment by jefferylockett** [comment]
looks good

**Pull request merged**
